config/routes.rb
CompStorage::Application.routes.draw do
  resources :trees

  resources :nodes

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/node.rb
class Node < ActiveRecord::Base
    belongs_to :tree
end

app/models/tree.rb
class Tree < ActiveRecord::Base
  has_many :nodes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render action: 'show', status: :created, location: @node }
      else
        format.html { render action: 'new' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:title, :description, :picture, :url, :is_in_storage, :is_borrowable, :is_sellable, :tree_id)
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]

  # GET /trees
  # GET /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tree }
      else
        format.html { render action: 'new' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.require(:tree).permit(:title, :picture, :tree_type)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompStorage</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :is_in_storage %><br>
    <%= f.check_box :is_in_storage %>
  </div>
  <div class="field">
    <%= f.label :is_borrowable %><br>
    <%= f.check_box :is_borrowable %>
  </div>
  <div class="field">
    <%= f.label :is_sellable %><br>
    <%= f.check_box :is_sellable %>
  </div>
  <div class="field">
    <%= f.label :tree_id %><br>
    <%= f.text_field :tree_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Url</th>
      <th>Is in storage</th>
      <th>Is borrowable</th>
      <th>Is sellable</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.title %></td>
        <td><%= node.description %></td>
        <td><%= node.picture %></td>
        <td><%= node.url %></td>
        <td><%= node.is_in_storage %></td>
        <td><%= node.is_borrowable %></td>
        <td><%= node.is_sellable %></td>
        <td><%= link_to 'Show', node %></td>
        <td><%= link_to 'Edit', edit_node_path(node) %></td>
        <td><%= link_to 'Destroy', node, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @node.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @node.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @node.picture %>
</p>

<p>
  <strong>Url:</strong>
  <%= @node.url %>
</p>

<p>
  <strong>Is in storage:</strong>
  <%= @node.is_in_storage %>
</p>

<p>
  <strong>Is borrowable:</strong>
  <%= @node.is_borrowable %>
</p>

<p>
  <strong>Is sellable:</strong>
  <%= @node.is_sellable %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/trees/_form.html.erb
<%= form_for(@tree) do |f| %>
  <% if @tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% @tree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :tree_type %><br>
    <%= f.text_field :tree_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing tree</h1>

<%= render 'form' %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<h1>Listing trees</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Picture</th>
      <th>Node</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= tree.title %></td>
        <td><%= tree.picture %></td>
        <td><%= tree.tree_type %></td>
        <td><%= link_to 'Show', tree %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
        <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree', new_tree_path %>

app/views/trees/new.html.erb
<h1>New tree</h1>

<%= render 'form' %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tree.title %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @tree.picture %>
</p>

<p>
  <strong>Type:</strong>
  <%= @tree.tree_type %>
</p>

<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<p><%= link_to "Objects", controller:"nodes", action:"index" %></p>